### ISSUE TITLE
Crash on entering a world

### ISSUE THREAD

**Issue by seriousfreezing** [StartsMercury/luminous-no-shading#1]
https://paste.atlauncher.com/view/8b45999c-a3bb-4c7e-ae72-da4a2f28ff9d

[crash-2024-10-01_17.39.21-client.txt](https://github.com/user-attachments/files/17216238/crash-2024-10-01_17.39.21-client.txt)

**Comment by StartsMercury** [comment]
It should be fixed in `0.2.1`. Thanks! I wouldn't have noticed this simple mistake outside the dev environment.

**Comment by seriousfreezing** [comment]
Thank you for the speedy response and fixing!
