### ISSUE TITLE
Some issues with Iris Shaders

### ISSUE THREAD

**Issue by Vi-Tul** [StartsMercury/luminous-no-shading#2]
When using shaders with Iris Shaders mod, item form of light-emit blocks do not render in hands and when dropped
_Without shaders:_
![Without shaders](https://github.com/user-attachments/assets/e22814bb-3b6b-4885-9326-f16fe48d33ee)

_With shaders:_
![With shaders](https://github.com/user-attachments/assets/df9e8813-e2cb-4857-b84f-e383d2b3d139)
![With shaders](https://github.com/user-attachments/assets/29098cc6-5f5d-4738-b207-d53abd2816e7)

Also vanilla block entities do not render in hands, when placed and when dropped
![With shaders](https://github.com/user-attachments/assets/eb19673a-99a7-4918-b0f8-bf4d64b5ddde)

Tested with different shaders and using only with Sodium and Simply No Shading mods.

**Comment by Vi-Tul** [comment]
The same issue is happening with Totem No Shading mod - totem is just not rendering

**Comment by StartsMercury** [comment]
I don't think this/these mods can work with Iris' shaders. The fix then is for the mod to disable itself when a shader is enabled. I'll look into a fix for this and Totem No Shading (when I get the time).

**Comment by Vi-Tul** [comment]
If you could, it would be great if you kept no shading for light-emit blocks and block entities in GUIs, this feature works as intended with shaders.

**Comment by StartsMercury** [comment]
I'll keep that in mind! I will try figuring that out
