### ISSUE TITLE
Wrong URLs in Modrinth description

### ISSUE THREAD

**Issue by Vi-Tul** [StartsMercury/luminous-no-shading#3]
![image](https://github.com/user-attachments/assets/500a2546-b29c-4388-8529-f4aa97c90938)
These two links leads to [modrinth.com/totem-no-shading](https://modrinth.com/totem-no-shading) and [modrinth.com/simply-no-shading](https://modrinth.com/simply-no-shading), but they are missing "mod/" which leads to 404 page. 
They should be [modrinth.com/mod/totem-no-shading](https://modrinth.com/mod/totem-no-shading) and [modrinth.com/mod/simply-no-shading](https://modrinth.com/mod/simply-no-shading)

**Comment by StartsMercury** [comment]
Fixed! And thank you, I wouldn't have noticed!
